kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: hk8s
  namespace: dennis-lab
  annotations:
    openshift.io/host.generated: 'true'
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  host: hello-kubernetes-dennis-lab.apps.ocp49.experteam.com.tw
  to:
    kind: Service
    name: hk8s-svc
    weight: 100
  port:
    #targetPort: 8080
    targetPort: 80
  wildcardPolicy: None
